#!/bin/sh
# stop on all errors
set -euf

# death after SIGINT
trap 'exit' INT

# switch to script directory
cd "$(dirname "$0")"

USAGE_HELP="Usage: nchart { COMMAND }"

# check if arguments are empty
if [ -z "${*+x}" ]; then
    echo "${USAGE_HELP}"; exit 1
fi

# remove subcommand from arguments through shift
NCHART_COMMAND="${1}"; shift
if [ -z "${*+x}" ]; then
    NCHART_ARGS=""
else
	NCHART_ARGS="${*}"
fi

# i.e. source ./scripts/env.sh
.  ./scripts/env.sh;

# scratch directory must be set
if [ -z "${NCHART_SCRATCH}" ]; then
    echo "scratch directory must be set"; exit 1
fi
# create scratch directory if it doesn't exist
mkdir -p "${NCHART_SCRATCH}"

# get name of current top level directory, uuid used if not given
TOP_DIR="$(basename "$PWD")"
if scripts/validate_uuid.sh "${TOP_DIR}"; then
	UUID_FROM_DIR="${TOP_DIR}"
fi

case "${NCHART_COMMAND}" in
	new )
		if [ -z "${NCHART_GOLDEN}" ]; then
			./scripts/new_chart_scratch.sh "${NCHART_ARGS}"
		else
			./scripts/new_chart_golden.sh "${NCHART_ARGS}"
		fi
		;;
	init )
		./scripts/init_chart.sh "${NCHART_ARGS}"
		;;
    open )
		./scripts/open_chart.sh "${NCHART_ARGS}"
		;;
    sync )
		./scripts/commit_chart.sh "${NCHART_ARGS}"
		./scripts/sync_chart.sh "${NCHART_ARGS}"
		;;
    close )
		./scripts/commit_chart.sh "${NCHART_ARGS}"
		./scripts/sync_chart.sh "${NCHART_ARGS}"
		./scripts/close_chart.sh "${NCHART_ARGS}"
		;;
	* )
		echo "${USAGE_HELP}"; exit 1;;
esac
