#!/bin/sh
# stop on all errors
set -euf

z40="0000000000000000000000000000000000000000"
emptytree=$(git hash-object -t tree /dev/null)

while read -r old_sha new_sha refname; do
    if [ "$old_sha" = "$z40" ]; then
        against="${emptytree}"
    else
        against="${old_sha}"
    fi
    if [ "$refname" = "main" ]; then
        if test $(git diff --name-only --diff-filter=ACMRT -z "${against}" "${new_sha}" | LC_ALL=C tr '\000' '\012' |
	    grep -v '^\([0-9]\{4\}[0-1][0-9][0-3][0-9]T[0-2][0-9][0-5][0-9][0-5][0-9]Z\)\?_.*$' | wc -c) != 0; then
            exit 1
        fi
    else
        exit 1
    fi
done

